config/routes.rb
Rails.application.routes.draw do
  resources :addresses do
    member do
      patch :mark_sent
    end
  end
  
  resources :people do
    collection do
      get :add_child_row
    end
  
    member do
      patch :add_child
      patch :remove_child
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "addresses#index"  
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address, :optional => true
  
  belongs_to :spouse, :class_name => "Person", :optional => true
  has_many :children, :class_name => "Person", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Person", :optional => true
  
  accepts_nested_attributes_for :address, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :spouse, :allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :children, :allow_destroy => true, reject_if: :validate_child
  
  def self.child_placeholder_value
    return "New child"
  end
  
  def validate_child(child)
    # Returns true if the attributes are invalid
    if (child[:firstName].blank? && child[:lastName].blank?)
      Rails.logger.debug "Rejecting child because firstName and lastName are blank: #{child.inspect}"
      return true
    elsif child[:firstName] == Person.child_placeholder_value
      Rails.logger.debug "Rejecting child because firstName is the placeholder are blank: #{child.inspect}"
      return true
    else
      Rails.logger.debug "Accepting nested child: #{child.inspect}"
      return false
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy, :remove_child]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end
  
  # GET /people/1
  # GET /people/1.json
  def show
    @address = @person.address
    @spouse = @person.spouse
    @children = @person.children
    
    if (@children.empty? && @spouse && !@spouse.children.empty?)
      @children = @spouse.children
    end
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    @person.children.build()
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        if (@person.address.addressee.nil?)
          @person.address.addressee = @person
          @person.address.save
        end
        
        if (@person.spouse && @person.spouse.lastName == "")
          @person.spouse.lastName = @person.lastName
          @person.spouse.save
        end
        
        unless (@person.children.empty?)
          @person.children.each do |child|
            if (child.lastName == "")
              child.lastName = @person.lastName
              child.save
            end
          end
        end
        
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    Rails.logger.debug "Running Person.update(#{params.inspect})"
    
    respond_to do |format|
      if @person.update(person_params)
        if (@person.address.addressee.nil?)
          @person.address.addressee = @person
          @person.address.save
        end
        
        if (@person.spouse)
          @person.spouse.address = @person.address
          @person.spouse.spouse = @person
          @person.spouse.save
        end
        
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_child
    Rails.logger.debug "remove_child: #{params.inspect}"
    child = Person.find(params[:child_id])

    @person.children.delete(child) if (@person)
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
      if (@person.parent)
        @person = @person.parent
      end
      
      if (@person.address.addressee && @person != @person.address.addressee)
        @person = @person.address.addressee
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:lastName, :firstName, :suffix, :address_attributes => [:id, :street1, :street2, :city, :state, :zip, :lastSent, :_destroy], :spouse_attributes => [:id, :lastName, :firstName, :suffix, :_destroy], :children_attributes => [:id, :lastName, :firstName, :suffix, :_destroy])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def setup_person(person)
    person.build_address() if (person.address.nil?)
    person.build_spouse() if (person.spouse.nil?)
    person.children.build() if (person.children.empty?)
    
    return person
  end
  
  def full_name(person)
    return "" if person.nil?
    full_name = "#{person.firstName} #{person.lastName}"
    full_name += ", #{person.suffix}" unless (person.suffix.blank?)
    
    return h(full_name)
  end
  
  def resident_names(person)
    resident_names = Array.new()
    
    if (person.firstName.blank?)
      return h("The #{person.lastName.pluralize}")
    elsif (person.spouse && person.lastName != person.spouse.lastName)
      resident_names << full_name(person)
      resident_names << full_name(person.spouse)
    elsif (person.spouse)
      resident_names << person.firstName
      resident_names << person.spouse.firstName
    else
      resident_names << person.firstName
    end
    
    unless (person.children.empty?)
      person.children.each do |child|
        if (child.lastName != person.lastName)
          resident_names << full_name(child)
        else
          resident_names << child.firstName
        end
      end
    end
      
    return h("#{resident_names.join(", ")}")
  end
    
  def add_child_link(text, person)
    if (person && person.id)
      link_to(text, add_child_person_path( person ), :remote => true, :method => :patch )
    else
      link_to(text, add_child_row_people_path, :remote => true )
    end    
  end
  
  def remove_child_link(text, child)
    link_to(text, remove_child_person_path( child ), :remote => true, :method => :patch)
  end  
end

app/views/people/_child_row.html.erb
<tr id="<%= h("child_new") %>" class="child">
 <% child_id = (Time.now.to_f * 100000).to_i %>
 <td><%= text_field_tag "person[children_attributes][#{child_id}][firstName]", "", :placeholder => Person.child_placeholder_value %></td>
 <td><%= text_field_tag "person[children_attributes][#{child_id}][lastName]", "" %></td>
</tr>

app/views/people/_children_table.html.erb
  <table id="children_table" class="children_table">
    <thead><tr><th id="column_0">Children</th><th id="column_1"></th><th id="column_2"></th></tr></thead>
    <% row_num = 0 %> 
    <%= form_for person do |form| %>
      <%= form.fields_for :children, :child_index => ->{ (Time.now.to_f * 10000).to_i } do |ff| %>
        <tr id="<%= h("child_#{ff.index}") %>" class="direction">              
          <td>
            <%= ff.text_field :firstName %>
          </td>
          <td>
            <%= ff.text_field :lastName %>
          </td>
          <td>
            <% if (ff.object.persisted?) %>
              <%= link_to "Delete", remove_child_person_path(person, :child_id => ff.object.id), :remote => :true, :method => :patch %>
            <% end %>
          </td>
        </tr>
        <% row_num += 1 %>
      <% end %>
    <% end %>
    <tfoot><tr>
      <td><span class='add-child-link'><%= add_child_link("Add Child", person) %></span></td>
    </tr></tfoot>
  </table>

app/views/people/_form.html.erb
<%= form_with(model: setup_person(person), local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @form = form %>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>      
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
    <%= form.label :suffix %>
    <%= form.text_field :suffix %> 
  </div>
    
  <%= form.fields_for :address, :child_index =>  ->{ (Time.now.to_f * 1000000).to_i  } do |ff| %>
    <div class="field">
      <%= ff.label :street1 %>
      <%= ff.text_field :street1, id: :address_street1 %>
    </div>

    <div class="field">
      <%= ff.label :street2 %>
      <%= ff.text_field :street2, id: :address_street2 %>
    </div>

    <div class="field">
      <%= ff.label :city %>
      <%= ff.text_field :city, id: :address_city %>
    </div>

    <div class="field">
      <%= ff.label :state %>
      <%= ff.text_field :state, id: :address_state %>
    </div>

    <div class="field">
      <%= ff.label :zip %>
      <%= ff.text_field :zip, id: :address_zip %>
    </div>
  <% end %>

<strong>Spouse</strong>
  <%= form.fields_for :spouse, :child_index =>  ->{ (Time.now.to_f * 1000000).to_i  } do |ff| %>
    <div class="field">
      <%= ff.label :firstName %>
      <%= ff.text_field :firstName %>
      <%= ff.label :lastName %>
      <%= ff.text_field :lastName %>
    </div>
  <% end %>

  <%= render :partial => "children_table", :locals => { :person => person } %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_new_child.html.erb
<tr class="child" id="child_new">
<% new_child = Person.new %>
<%= form_for person do |f| %>
  <%= f.fields_for :children, new_child, :child_index => ->{ (Time.now.to_f * 1000000).to_i } do |ff| %>
    <td>
      <%= ff.text_field :firstName %>
    </td>
    <td>
      <%= ff.text_field :lastName %>
    </td>
    <td>
    &nbsp;
    </td>
  <% end %>
<% end %>
</tr>

app/views/people/_person_row.html.erb
<div id="<%= row_id %>">
<tr>
  <% view_key = person.lastName %>
  <% if (person.spouse && person.spouse.lastName != person.lastName) %>
    <% view_key += "/#{person.spouse.lastName}" %>
  <% end %>
  
  <td><%= link_to(view_key, person) %></td>
  <td><%= h("(#{resident_names(person)})") %></td>
  <% if (person.address) %>
    <td><%= person.address.street1 %></td>
    <td><%= person.address.street2 %></td>
    <td><%= person.address.city %></td>
    <td><%= person.address.state %></td>
    <td><%= person.address.zip %></td>
    <td><%= h("Last sent: #{person.address.lastSent}") if (person.address.lastSent) %></td>  
  <% else %>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  <% end %>
  <td>
  <% if (person.children.empty?) %>
    &nbsp;
  <% else %>
    <% child_names = Array.new %>
    <% person.children.each do |child| %>
      <% child_names << child.firstName %>
    <% end %>
    <%= h(child_names.join(", ")) %>
  <% end %>
  </td>
  <td>
    <% if (person.address) %>
      <%= link_to('Mark Sent', mark_sent_address_path(person.address), :remote => true, :method => :patch) %>
    <% else %>
      &nbsp;
    <% end %>
  </td>
  <td><%= link_to 'Edit', edit_person_path(person) %></td>
  <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
</div>

app/views/people/add_child.js.erb
var newRow = document.createElement('tr');
newRow.innerHTML="<%= j( render :partial => 'new_child', :locals => { :person => @person } ) %>";


var child_count = document.getElementsByClassName('child').length;
var childrenTable = document.getElementById("children_table");
var tableBody = childrenTable.getElementsByTagName("tbody")[0];

console.log("Creating new Child (" + child_count + ") for Person...");
newRow.className = 'child'
newRow.id = "child_" + child_count;
tableBody.appendChild(newRow);

app/views/people/add_child_row.js.erb
var newRow = document.createElement('tr');
newRow.innerHTML="<%= j( render :partial => 'child_row', :locals => {:child => Person.new()}) %>";

var task_count = document.getElementsByClassName('child').length;
var tasksTable = document.getElementById("children_table");
var tableBody = tasksTable.getElementsByTagName("tbody")[0];

console.log("Creating new Child row (" + task_count + ") for submission...");
newRow.className = 'child'
newRow.id = task_count;
tableBody.appendChild(newRow);

app/views/people/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', person: @person %>

<%= link_to 'Cancel', @person %> |
<%= link_to 'Back to Addresses', addresses_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spouse</th>
      <th>Street</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Children</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <%= render :partial => "person_row", :locals => {:person => person} %>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/mark_sent.js.erb
document.getElementById("address_<%= @person.id %>").innerHTML="<%= j( render :partial => 'person_row', :locals => { :person => @person } ) %>";

app/views/people/new.html.erb
<h1>New Address</h1>

<%= render 'form', person: @person %>

<%= link_to 'Cancel', addresses_path %>

app/views/people/remove_child.js.erb
document.getElementById("children_table").innerHTML = "<%= j( render :partial => "children_table", :locals => { :person => @person }) %>";

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= h(@person.lastName) %><%= h("/#{@spouse.lastName}") if (@spouse && @spouse.lastName != @person.lastName) %></h1>
  <%= full_name(@person) %><%= h(" & #{full_name(@spouse)}") if @spouse %>
<br>
  <%= h(@address.street1) %><br>
  <% unless (@address.street2.blank?) %>
    <%= h(@address.street2) %><br>
  <% end %>
  <%= h("#{@address.city}, #{@address.state} #{@address.zip}") %>
</p>
<% if (@children) %>
<p>
<strong>Children:</strong>
  <% @children.each do |child| %>
    <% if (child.lastName != @person.lastName) %>
    <li><%= full_name(child) %><br>
    <% else %>
    <li><%= h(child.firstName) %>
    <% end %>
  <% end %>
</p>
<% end %>
<%= link_to 'Edit Address', edit_person_path(@person) %> | 
<%= link_to 'New Address', new_person_path %> | 
<%= link_to 'Back to Addresses', addresses_path %>