config/routes.rb
Rails.application.routes.draw do
  resources :addresses do
    member do
      patch :mark_sent
    end
  end
  
  resources :people do
    collection do
      get :add_child_row
    end
  
    member do
      patch :add_child
      patch :remove_child
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "addresses#index"  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.includes(:addressee).order("people.lastName ASC")
  end
  
  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
    @address.residents.build() if (@address.residents.empty?)
    @residents = @address.residents
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    Rails.logger.debug "Running Address.update(#{params.inspect})"
    
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_sent
    @address = Address.find(params[:id])
    @address.lastSent = Date.today.year.to_s
    respond_to do |format|
      if (@address.save)
        format.js
      else
        format.js
      end
    end
  end
      
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:lastName, :firstName, :street1, :street2, :city, :state, :zip, :lastSent, :residents_attributes => [:id, :lastName, :firstName, :suffix, :_destroy])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
  def setup_address(address)
    address.build_resident() if (address.resident.nil?)
    address.resident.build_spouse() if (address.resident.spouse.nil?)
    return address
  end
  
  def full_resident_name(resident)
    return "" if resident.nil?
    
    return h("#{resident.firstName} #{resident.lastName}")
  end
end

app/views/addresses/Mark_sent.js.erb
document.getElementById("address_<%= @address.id %>").innerHTML="<%= j( render :partial => 'person_row', :locals => { :person => @address.addressee } ) %>";

app/views/addresses/_address_row.html.erb
<div id="address_<%= address.id %>">
  <%= render :partial => "people/person_row", :locals => {:person => address.addressee} %>
</div>

app/views/addresses/_form.html.erb
<%= form_with(model: setup_address(@address), local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :addressee, :child_index =>  ->{ (Time.now.to_f * 1000000).to_i  } do |ff| %>
    <div class="field">
      <%= ff.label :lastName %>
      <%= ff.text_field :lastName %>
      <%= ff.label :firstName %>
      <%= ff.text_field :firstName %>      
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street1 %>
    <%= form.text_field :street1, id: :address_street1 %>
  </div>

  <div class="field">
    <%= form.label :street2 %>
    <%= form.text_field :street2, id: :address_street2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :address_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :address_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :address_zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <%= render :partial => "people/person_row", :locals => {:person => address.addressee, :row_id => address.id} %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_person_path %>

app/views/addresses/mark_sent.js.erb
document.getElementById("address_<%= @address.id %>").innerHTML="<%= j( render :partial => 'people/person_row', :locals => { :person => @address.addressee } ) %>";

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if (@address.addressee) %>
    <%= full_resident_name(@address.addressee) %>
  <% end %>

  <%= h(@address.street1) %>
  <% unless (@address.street2.blank?) %>
    <%= h(@address.street2) %>
  <% end %>
  <%= h("#{@address.city}, #{@address.state} #{@address.zip}") %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back To Addresses', addresses_path %>